name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -B "${{ github.workspace }}/build"
        -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl
        -DCMAKE_BUILD_TYPE=Release
        -DBUILD_SHARED_LIBS=ON
        -S "${{ github.workspace }}"

    - name: Build
      run: |
        echo "::add-matcher::.github/problem-matchers/${{ matrix.problem_matcher }}.json"
        cmake --build ${{ github.workspace }}/build --config Release

    - name: Create Installer
      run: |
        cmake --build ${{ github.workspace }}/build --config Release --target package

    - name: Create Release
      uses: ncipollo/release-action@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        generateReleaseNotes: true
        artifacts: "${{ github.workspace }}/build/Release/*.msi"
        artifactErrorsFailBuild: true
        token: ${{ github.token }}
